name = "timer"
version = "2.0.0"
license = "MIT"
author = "ZUO Zhihua"
maintainer = "zuo.zhihua@qq.com"
copyright = "Copyright 2023, ZUO Zhihua"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
